# Метрические алгоритмы. Практика

В этом домашнем задании вы будете решать задачу классификации бутылок вина по различным характеристикам.

## Импорт библиотек, установка константных значений

In [147]:
import pandas as pd
import numpy as np

In [148]:
RANDOM_STATE = 42
TRAIN_SIZE = 0.75

In [149]:
rng = np.random.default_rng(RANDOM_STATE)

## Загрузка данных

In [150]:
from sklearn.datasets import load_wine

data = load_wine(as_frame=True)

x = data.data
y = data.target

## Задание 1

Посмотрите на количество классов и количество объектов каждого класса в датасете.

**Вопрос**:  
Сколько классов в задаче?

In [151]:
# ваш код здесь
y.value_counts()

target
1    71
0    59
2    48
Name: count, dtype: int64

## Задание 2

Мы имеем дело с многоклассовой классификацией. Кроме того, классы не очень хорошо сбалансированы, поэтому для оценки качества модели метрика *accuracy* не подойдет.

Разбейте данные на тренировочную и тестовую части:  
тестовая часть - 25% от всех данных, зафиксируйте `random_state = RANDOM_STATE`.

In [152]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=RANDOM_STATE)

**Вопрос:**

Все ли признаки в данных одного масштаба?  
Проверьте это, выведя основные числовые характеристики матрицы `X_train` методом `describe` из библиотеки `pandas`.

По полученной таблице числовых характеристик определите, какой признак измеряется в сотнях?  
(если вариантов несколько, выберите признак с наибольшим средним значением).

In [153]:
# ваш код здесь
xtrain.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,12.972857,2.386842,2.362180,19.433835,100.759398,2.277068,2.021203,0.363534,1.608647,5.017594,0.959444,2.610000,742.992481
std,0.829993,1.098905,0.280606,3.467312,14.999571,0.645696,1.005537,0.126923,0.576964,2.202516,0.234545,0.729961,306.867593
min,11.030000,0.890000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.420000,1.740000,0.480000,1.270000,278.000000
25%,12.290000,1.640000,2.210000,17.200000,88.000000,1.700000,1.200000,0.260000,1.250000,3.250000,0.780000,1.830000,500.000000
50%,12.990000,1.900000,2.360000,19.400000,98.000000,2.230000,2.140000,0.340000,1.560000,4.800000,0.970000,2.810000,675.000000
75%,13.690000,3.170000,2.540000,21.500000,108.000000,2.800000,2.880000,0.450000,1.960000,6.130000,1.120000,3.200000,970.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,10.800000,1.710000,4.000000,1547.000000

In [154]:
x[:5]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

## Задание 3

KNN требует того, чтобы все признаки были одного масштаба, поэтому масштабируйте данные при помощи `StandardScaler`.

Напоминаем, что обучать метод нужно только по тренировочным данным, а применять и к трейну, и к тесту.

После применения `StandardScaler` преобразуйте `X_train` и `X_test` к типу `pd.DataFrame`, названия новых объектов оставьте `X_train` и `X_test`.

In [155]:
from sklearn.preprocessing import StandardScaler

# ваш код здесь
scaler = StandardScaler()
xtrain = pd.DataFrame(scaler.fit_transform(xtrain), columns=xtrain.columns)
xtest = pd.DataFrame(scaler.transform(xtest), columns=xtest.columns)

Обучите KNN с параметрами по умолчанию на тренировочных данных и сделайте предсказание на тесте.

In [156]:
from sklearn.neighbors import KNeighborsClassifier

# ваш код здесь
knn = KNeighborsClassifier()
knn.fit(xtrain, ytrain)
pred = knn.predict(xtest)

Будем измерять качество модели по метрике weighted $f1$-score.

Чтобы выбрать тип усреднения (micro, macro, weighted) в функции `f1_score` необходимо задать этот тип в гиперпараметре `average`.

Вычислите $f1$-score на тестовых данных.

**Вопрос:**

Чему равен $f1$-score на тестовых данных?

In [157]:
from sklearn.metrics import f1_score

# ваш код здесь
f1 = f1_score(ytest, pred, average='weighted')
print(f'Weighted f1 score = {f1}')

Weighted f1 score = 0.9550512333965844

## Задание 4

Попробуем улучшить модель.

Подберите оптимальное количество соседей (`n_neighbors`) из диапазона *от 3 до 30 с шагом 2* и веса соседей (`weights`):  
`uniform`, `distance` по кросс-валидации с тремя фолдами на тренировочных данных.

Используйте `GridSearchCV` и метрику `f1_weighted`.

In [158]:
from sklearn.model_selection import GridSearchCV

# ваш код здесь

params = {'n_neighbors' : np.arange(3,30,2),
          'weights': ['uniform','distance']}

new_knn = GridSearchCV(KNeighborsClassifier(), params, cv=3, scoring='f1_weighted').fit(xtrain, ytrain)

print(f'Лучшие параметры: {new_knn.best_params_}')
print(new_knn.best_score_)

Лучшие параметры: {'n_neighbors': np.int64(19), 'weights': 'distance'}
0.9623290498688742

Возьмите best_estimator_, полученный при обучении GridSearchCV и с помощью него  
сделайте предсказание на тесте и вычислите метрику `f1_weighted`.

In [159]:
# ваш код здесь
best_knn = new_knn.best_estimator_

new_pred = best_knn.predict(xtest)
print(f'Предсказание при лучших параметрах: {f1_score(ytest, new_pred, average='weighted')}')

Предсказание при лучших параметрах: 0.9550512333965844

**Вопрос:**

Удалось ли при помощи подбора гиперпараметров улучшить качество модели на тестовых данных?

## Задание 5

Выведите на экран матрицу ошибок.

Используйте модель с подобранными при помощи `GridSearch` гиперпараметрами.

**Вопрос:**  
По этой матрице определите, какие классы между собой путает модель?

In [160]:
from sklearn.metrics import confusion_matrix

# ваш код здесь
confusion_matrix(ytest, new_pred)

array([[15,  0,  0],
       [ 1, 16,  1],
       [ 0,  0, 12]])

## Бонус (эксперименты с LSH)

Скопируйте все функции из [ноутбука в уроке "Быстрый поиск соседей"](https://colab.research.google.com/drive/181MMOcTnzdMVzJr0pWzqtEG0-BV9BIHH).

In [161]:
# ваш код здесь
def knn_search(query, data, k=5):

    dists = np.sqrt(np.sum((data - query) ** 2, axis=1))  # вычисляем расстояния от объекта query до всех точек датасета
    inds = np.argsort(dists)  # сортируем по возрастанию расстояний
    inds_k = inds[:k]         # берем top-k точек с наименьшими расстояниями

    return data[inds_k], dists[inds_k]

def generate_hyperplanes(data, bucket_size=16):
    m = data.shape[0]            # число объектов
    n = data.shape[1]            # число признаков
    b = m // bucket_size         # количество корзин
    h = int(np.log2(b))          # количество гиперплоскостей
    H = rng.normal(size=(h, n))  # гиперплоскости, заданные своими нормалями
    return H


def hamming_hash(data, hyperplanes):
    b = len(hyperplanes)
    hash_key = (data @ hyperplanes.T) >= 0

    dec_vals = np.array([2 ** i for i in range(b)], dtype=int)
    hash_key = hash_key @ dec_vals

    return hash_key


def locality_sensitive_hash(data, hyperplanes):
    hash_vals = hamming_hash(data, hyperplanes)
    hash_table = {}
    for i, v in enumerate(hash_vals):
        if v not in hash_table:
            hash_table[v] = set()
        hash_table[v].add(i)

    return hash_table


def approx_knn_search(query, data, k=5, bucket_size=16):
    candidates = set()

    hyperplanes = generate_hyperplanes(data)
    hash_table = locality_sensitive_hash(data, hyperplanes) # формируем хеш-таблицу по датасету

    query_hash = hamming_hash(query, hyperplanes)
    if query_hash in hash_table:
        candidates = candidates.union(hash_table[query_hash])
    candidates = np.stack([data[i] for i in candidates], axis=0) # находим кандидатов = объекты, попадающие с query в одну корзину

    return knn_search(query, candidates, k=k) # с помощью KNN ищем ближайших соседей только из найденных кандидатов

При помощи `knn_search` найдите ближайших соседей к вину `X_test.iloc[0]` в **тренировочных** данных.

Обратите внимание, что функция `knn_search` принимает на вход `np.array`, а не `pd.DataFrame`. Поэтому переведите аргументы в `np.array`, приписав к необходимому объекту $X$: `X.values`.

In [184]:
%%time

# ваш код здесь
neighbors, dists = knn_search(xtest.iloc[0].values, xtrain.values)
print(f'Ближайшие соседи: {neighbors[0]}')
print(f'Расстояние до соседей: {dists[0]}')

Ближайшие соседи: [ 1.50827494  1.46438454  0.52877788 -1.80468392  1.82295821  1.12384935
  1.01701759 -1.2933229   0.82004316  0.03755595 -0.29719787  1.26510707
  0.05563253]
Расстояние до соседей: 1.7873320988662762
CPU times: total: 0 ns
Wall time: 612 μs

Выведите на экран признаки объекта `X_test.iloc[0]` и признаки ближайшего найденного соседа.

In [179]:
# ваш код здесь
xtest.iloc[0]

alcohol                         0.806832
malic_acid                      0.651425
ash                             0.707637
alcalinity_of_ash              -1.225688
magnesium                       1.019911
total_phenols                   0.657478
flavanoids                      1.007035
nonflavanoid_phenols           -1.530581
proanthocyanins                 0.089343
color_intensity                 0.037556
hue                             0.002381
od280/od315_of_diluted_wines    1.031337
proline                         0.333672
Name: 0, dtype: float64

In [180]:
xtrain.iloc[neighbors[0]]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
1,-1.079807,-0.280281,-2.368742,-0.559842,-0.251581,-0.073170,0.148537,-0.818807,-0.362996,-0.782781,1.329088,0.481291,-0.107920
1,-1.079807,-0.280281,-2.368742,-0.559842,-0.251581,-0.073170,0.148537,-0.818807,-0.362996,-0.782781,1.329088,0.481291,-0.107920
0,0.226328,-0.024519,1.101127,-0.241394,0.016101,0.812935,1.216668,-0.502463,2.090070,0.301887,0.301960,0.770065,1.445831
132,-0.765367,0.057691,0.349919,0.453402,-0.184661,0.439838,0.088642,-0.186120,-0.519574,-1.010652,-0.682371,1.058840,-0.997647
1,-1.079807,-0.280281,-2.368742,-0.559842,-0.251581,-0.073170,0.148537,-0.818807,-0.362996,-0.782781,1.329088,0.481291,-0.107920
1,-1.079807,-0.280281,-2.368742,-0.559842,-0.251581,-0.073170,0.148537,-0.818807,-0.362996,-0.782781,1.329088,0.481291,-0.107920
1,-1.079807,-0.280281,-2.368742,-0.559842,-0.251581,-0.073170,0.148537,-0.818807,-0.362996,-0.782781,1.329088,0.481291,-0.107920
132,-0.765367,0.057691,0.349919,0.453402,-0.184661,0.439838,0.088642,-0.186120,-0.519574,-1.010652,-0.682371,1.058840,-0.997647
0,0.226328,-0.024519,1.101127,-0.241394,0.016101,0.812935,1.216668,-0.502463,2.090070,0.301887,0.301960,0.770065,1.445831
0,0.226328,-0.024519,1.101127,-0.241394,0.016101,0.812935,1.216668,-0.502463,2.090070,0.301887,0.301960,0.770065,1.445831
0,0.226328,-0.024519,1.101127,-0.241394,0.016101,0.812935,1.216668,-0.502463,2.090070,0.301887,0.301960,0.770065,1.445831
1,-1.079807,-0.280281,-2.368742,-0.559842,-0.251581,-0.073170,0.148537,-0.818807,-0.362996,-0.782781,1.329088,0.481291,-0.107920
0,0.226328,-0.024519,1.101127,-0.241394,0.016101,0.812935,1.216668,-0.502463,2.090070,0.301887,0.301960,0.770065,1.445831

**Вопрос:**

Можно ли сказать, что в тренировочных данных есть вино, почти такое же как `X_test.iloc[0]`? (все признаки почти одинаковые)

Какое расстояние между объектом запроса и первым ближайшим соседом?

Теперь найдите ближайшего соседа при помощи `approx_knn_search`.

In [187]:
%%time

# ваш код здесь
hash_table = locality_sensitive_hash(xtrain.values, generate_hyperplanes(xtrain.values))

neighbors, dists = approx_knn_search(xtest.iloc[0].values, xtrain.values)
print(f'Ближайшие соседи: {neighbors[0]}')
print(f'Расстояние до соседей: {dists[0]}')

Ближайшие соседи: [ 1.04870892  1.58313141  0.06374382  0.01915477 -0.78694635 -0.74163538
 -1.18912249  0.92108376 -0.08463358  1.8195103  -1.6667021  -1.33386289
 -0.86026283]
Расстояние до соседей: 5.653136339639179
CPU times: total: 0 ns
Wall time: 1.5 ms

Ближайший сосед при помощи KNN+LSH может быть найден не точно или не с первого запуска.  
Запустите последнюю ячейку несколько раз и убедитесь, что ближайший сосед находится верно за несколько запусков.

**Вопрос:**

Запустите `knn_search` и `appox_knn_search` несколько раз и сравните время запусков. Какой из подходов в этой задаче работает быстрее?